Feature/admin events
td-org-uit-no/tdctl-frontend pull request #40
Opened 2022-11-26 12:56 UTC by Sagensagen

# :warning: Dependent on tdctl_api/feature/participants :warning: 
# Admin events ++ 
 In order to conduct admin event i had to restructure events and participants which lead to adapt a lot of features, resulting in this quite huge PR.
## Admin event page

### :gear:  Settings
- Moved event settings here exclusively
- Added active/inactive toggle to settings
### Responses
Table of all members that has submitted as participants. 
Can Remove participants through table interface
![image](https://user-images.githubusercontent.com/34317459/204088206-d85c9f31-922a-4471-9de1-c637163ae502.png)

> Table might  be incorrect due to seeding data creating identical submitDates and includes multiple participants exceeding  maxParticipants. Should not be a problem in production. Can be fixed by seeding script.
TODO: food/Transport is hard coded into the form. Needs to be added to be selected. @otytlandsvik Is on this one i think?

### :bar_chart:  Statistics
General statistics for respective event
- How many needs food
- How many have submitted from total TD members
- Class distribution
- How many need Transport
- Participant submission X time chart
- Dietary restrictions overview
![image](https://user-images.githubusercontent.com/34317459/204088282-f8c69c1d-d84f-4e90-a6f5-97a7d96f8442.png)

> This page is computing a lot of stuff which might could have been solved by  the backend and additional api's. I have not measured any overhead, but it is not critical and works fine as is. Time chart is not scaling depending on inputs, and  can be optimized in future. 

### :page_facing_up: Export event details if  event data needed in sheet format. 
# :purple_square: Eventbody
Added a modal+form to appear if event requires participant to select food/transport/dietary restrictions.
Added event/admin navigation button for admins
![image](https://user-images.githubusercontent.com/34317459/204090086-91467d52-c964-4a53-a316-6b4b88afb74c.png)

# :classical_building:  Event & participant model
Changed both models to fit api
# Other
## Toggle molecule
Changed color to  purple/theme color for theme consistency
Added initial value to prefix its state when binding
## Icon 
Extended props to take optional color
## api
Added deleteParticipant api

2022-12-08 17:57 UTC, FredrikMorstad requested changes
Left some comments, that should to be fixed

2022-12-08 19:03 UTC, Sagensagen commented on package.json
> +    "sass": "^1.55.0"
@FredrikMorstad This was inherited from master branch. Should be moved to "dependencies"?

2022-12-08 19:06 UTC, Sagensagen commented on src/components/atoms/icons/icon.tsx
> +const Icon = ({ type, size = 1, color = 'primary', onClick }: Props) => (
`primary` does not trigger anything and base color is white. Can be misinterpreted, change to white.

2022-12-08 19:16 UTC, Sagensagen commented on src/components/molecules/event/eventExport/eventExport.tsx
> +    const request = new Request(baseUrl + 'event/' + url + '/export', {
Initially i tried that without success. Leeched of the get_image request to make it work.

2022-12-08 19:18 UTC, Sagensagen commented on src/components/molecules/event/eventButton/EventButton.tsx
> +    }
Yes, due to the buttonactions are "booelean" in terms of they cannot handle conditions. This was necessary to verify if join request needed any payload.

2022-12-09 07:11 UTC, FredrikMorstad commented on src/components/molecules/event/eventExport/eventExport.tsx
> +    const request = new Request(baseUrl + 'event/' + url + '/export', {
jeep, I did the same as well:mag: I think we can add a comment for later restructure :label:

2022-12-09 07:13 UTC, FredrikMorstad commented on src/components/molecules/event/eventButton/EventButton.tsx
> +    }
make sense :+1:

2022-12-11 11:25 UTC, FredrikMorstad requested changes
Some small changes that needs to be added otherwise LGTM :+1:

2022-12-11 11:25 UTC, FredrikMorstad commented on src/components/pages/admin/AdminPage.tsx
> +import { EventTable } from 'components/molecules/tables';
Can be imported from same file

2022-12-11 13:35 UTC, Sagensagen commented on src/components/molecules/event/eventStatistics/EventStatistics.tsx
> +    }, {} as any);
nope :-1:

2022-12-11 15:18 UTC, FredrikMorstad approved these changes
LGTM :rocket:

2022-12-11 15:19 UTC, merged